<?php

return [
    /*
    |--------------------------------------------------------------------------
    | State Repository
    |--------------------------------------------------------------------------
    |
    | The repository used to persist workflow state.
    |
    | Supported: "null", "session", "eloquent"
    |
    | - null: No persistence (stateless)
    | - session: Store in the browser session (deprecated)
    | - eloquent: Store in database (recommended; requires migration)
    |
    */
    'repository' => env('WORKFLOWS_REPOSITORY', 'eloquent'),

    /*
    |--------------------------------------------------------------------------
    | Middleware
    |--------------------------------------------------------------------------
    |
    | Middleware applied to all workflow routes by default.
    | Individual workflows and steps can override this using the middleware()
    | method or #[StepMiddleware] attribute.
    |
    */
    'middleware' => ['web'],

    /*
    |--------------------------------------------------------------------------
    | Middleware Precedence
    |--------------------------------------------------------------------------
    |
    | How middleware should be combined when multiple levels are defined.
    |
    | Supported: "override", "merge"
    |
    | - override: Step middleware completely replaces workflow/global middleware
    | - merge: Step, workflow, and global middleware are all combined
    |
    */
    'middleware_precedence' => env('WORKFLOWS_MIDDLEWARE_PRECEDENCE', 'override'),

    /*
    |--------------------------------------------------------------------------
    | Resume Links
    |--------------------------------------------------------------------------
    |
    | Configuration for signed resume URLs generated by resumeUrlFor().
    | Resume links require the Eloquent state repository.
    |
    */
    'resume' => [
        'default_expires_minutes' => env('WORKFLOWS_RESUME_EXPIRES', 1440),
    ],
];
